# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1521714966);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1521715086);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1521714606);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1521714846);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1521110970);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1521714726);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1521111090);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1521110850);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1521110220);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migrated-sync-button", true);
user_pref("browser.migration.version", 50);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1521714582);
user_pref("browser.onboarding.notification.prompt-count", 1);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-search,onboarding-tour-default-browser,onboarding-tour-sync,onboarding-tour-private-browsing,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-search,onboarding-tour-default-browser,onboarding-tour-sync");
user_pref("browser.onboarding.seen-tourset-version", 1);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1521714583311");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1521716387311");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1521714584076");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1521718184076");
user_pref("browser.search.countryCode", "RS");
user_pref("browser.search.region", "RS");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20171004085519");
user_pref("browser.slowStartup.averageTime", 1929);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20171004085519");
user_pref("browser.startup.homepage_override.mstone", "56.0");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"pocket-button\",\"screenshots_mozilla_org-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"pocket-button\",\"screenshots_mozilla_org-browser-action\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20180322);
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1521110223289");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("e10s.rollout.cohort", "test");
user_pref("e10s.rollout.cohortSample", "0.087470");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 22);
user_pref("extensions.e10s.rollout.blocklist", "");
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "50allmpc");
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.e10sMultiBlockedByAddons", false);
user_pref("extensions.getAddons.cache.lastUpdate", 1521714967);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20171004085519");
user_pref("extensions.lastAppVersion", "56.0");
user_pref("extensions.lastPlatformVersion", "56.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shield-recipe-client.first_run", false);
user_pref("extensions.shield-recipe-client.startupExperimentMigrated", true);
user_pref("extensions.shield-recipe-client.user_id", "f6b8fe04-cc0b-4675-954d-cbf31b3e6c05");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"0babf855-cd38-4482-baec-4d4cbb649a0e\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1521715190);
user_pref("media.gmp-manager.buildID", "20171004085519");
user_pref("media.gmp-manager.lastCheck", 1521714578);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1521112101);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugins.ctprollout.cohort", "user-changed-from-test");
user_pref("plugins.ctprollout.cohortSample", "0.464812");
user_pref("services.blocklist.addons.checked", 1521713846);
user_pref("services.blocklist.clock_skew_seconds", 1240);
user_pref("services.blocklist.gfx.checked", 1521713846);
user_pref("services.blocklist.last_update_seconds", 1521713846);
user_pref("services.blocklist.onecrl.checked", 1521713846);
user_pref("services.blocklist.plugins.checked", 1521713846);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1521112101);
user_pref("toolkit.startup.last_success", 1521714575);
user_pref("toolkit.telemetry.cachedClientID", "31515bd7-2a69-43d6-a69f-6564379a85ca");
user_pref("toolkit.telemetry.previousBuildID", "20171004085519");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
